package support;

public enum PageType {
    SITE_HOME,
    SITE_REGISTER_USER,
    SITE_SIGNIN_USER,
    SITE_EDIT_PROFILE,
    SITE_CHANGE_PASSWORD,
    SITE_FORGOT_PASSWORD,
    SITE_VIDEO_MANAGER
}
