package support;

public enum PageType {
    SITE_HOME,
    SITE_REGISTER_USER,
    SITE_SIGNIN_USER,
    SITE_EDIT_PROFILE,
    SITE_CHANGE_PASSWORD,
    SITE_FORGOT_PASSWORD,
    SITE_VIDEO_MANAGER,
    SITE_VIDEO_EDITOR,
    SITE_VIEW_VIDEO,
    SITE_MYFAVORITES,
    SITE_USER_MANAGER,
    SITE_USER_EDITOR,
    SITE_REPORTS_FAVORITE_USERS,
    SITE_REPORTS_FAVORITES,
    SITE_REPORTS_SHARED_FRIEND,
}
